version: '3.2'
services:
  virondb:
    image: postgres:9.6.5
    volumes:
      - viron-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: "-E UTF8 --no-locale"
    ports:
      - "5432:5432"

volumes:
  viron-data:
    driver: local
